"""
Copyright 2014-2016 Jiří Janoušek <janousek.jiri@gmail.com>

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met: 

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer. 
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import sys
from nuvolasdk.shkit import *
from nuvolasdk.defaults import BUILD_JSON

def gen_makefile():
	prefix = "/usr/local"
	metadata = readjson("metadata.json")
	build_json = readjson("build.json")
	
	for arg in sys.argv[1:]:
		try:
			name, value = arg.split("=", 1)
		except ValueError:
			continue
		if name == "--libdir":
			pass
		elif name == "--prefix":
			prefix = value
		elif name in ("CFLAGS", "CXXFLAGS"):
			pass
	
	app_id = metadata["id"]
	app_id_dashed = app_id.replace("_", "-")
	sdk_data = joinpath(fdirname(__file__), "data")
	
	all_files = ["metadata.json", "integrate.js", "README.md", "CONTRIBUTING.md", "CHANGELOG.md"]
	all_files.extend(glob("LICENSE*"))
	all_files.extend(build_json.get("extra_files", "").split(" "))
	
	files = ' '.join(all_files)
	
	install = [
		'install: all\n',
		'\tinstall -vCd $(APP_DIR)/$(ICONS_DIR)\n',
		'\tcp -v -t $(APP_DIR) $(FILES)\n',
	]
	uninstall = [
		'uninstall:\n',
		'\trm -rfv $(APP_DIR)\n'
	]
	icons_spec = build_json.get("icons", BUILD_JSON["icons"])
	icons = [
		'$(ICONS_DIR):\n',
		'\tmkdir -p $@\n'
		'$(ICONS_DIR)/%.svg: src/%.svg | $(ICONS_DIR)\n',
		'\t$(NUVOLA_SDK_DATA)/svg-optimize.sh $< $@\n'
		]
	
	for icon in icons_spec:
		path, *sizes = icon.split(' ')
		for size in sizes:
			if size.upper() == "SCALABLE":
				src = '$(ICONS_DIR)/' + fbasename(path)
				dest = "$(ICONS_DIR)/scalable.svg"
				icons.append('%s : %s | $(ICONS_DIR)\n\tcp -v $< $@\n' % (dest, src))
				install.append('\tcp -v -t $(APP_DIR)/$(ICONS_DIR) %s\n' % dest)
				install.append('\tmkdir -pv $(APP_DIR)/../../../icons/hicolor/scalable/apps || true\n')
				install.append('\tln -s -f -v -T ../../../../nuvolaplayer3/web_apps/$(APP_ID)/%s $(DEST)$(PREFIX)/share/icons/hicolor/scalable/apps/nuvolaplayer3_$(APP_ID).svg\n' % dest)
				uninstall.append('\trm -fv $(DEST)$(PREFIX)/share/icons/hicolor/scalable/apps/nuvolaplayer3_$(APP_ID).svg\n')
			else:
				src = '$(ICONS_DIR)/' + fbasename(path)
				dest = "$(ICONS_DIR)/%s.png" % size
				icons.append('%s : %s | $(ICONS_DIR)\n\t$(NUVOLA_SDK_DATA)/svg-convert.sh $< %s $@\n' % (dest, src, size))
				install.append('\tcp -v -t $(APP_DIR)/$(ICONS_DIR) %s\n' % dest)
				install.append('\tmkdir -pv $(APP_DIR)/../../../icons/hicolor/%sx%s/apps || true\n' % (size, size))
				install.append('\tln -s -f -v -T ../../../../nuvolaplayer3/web_apps/$(APP_ID)/%s $(DEST)$(PREFIX)/share/icons/hicolor/%sx%s/apps/nuvolaplayer3_$(APP_ID).png\n' % (dest, size, size))
				uninstall.append('\trm -fv $(DEST)$(PREFIX)/share/icons/hicolor/%sx%s/apps/nuvolaplayer3_$(APP_ID).png\n' % (size, size))
			all_files.append(dest)
		
	
	makefile = [
		'# Generated by Nuvola SDK - do not edit.\n',
		"APP_ID = ", app_id, "\n",
		"APP_ID_DASHED = ", app_id_dashed, "\n",
		"NUVOLA_SDK_DATA = ", sdk_data, "\n",
		'FILES = ', files, '\n',
		'ICONS_DIR ?= icons\n',
		'PREFIX ?= ', prefix, '\n',
		'DEST ?= \n',
		'APP_DIR = $(DEST)$(PREFIX)/share/nuvolaplayer3/web_apps/$(APP_ID)\n',
		'\n',
		'all: ', " ".join(all_files), '\n\n',
	]
	makefile.extend(icons)
	makefile.extend(install)
	makefile.extend(uninstall)
	makefile.extend((
		"clean:\n",
		"\trm -rf icons\n",
		"distclean: clean\n",
		"\trm -f Makefile\n"
	));
	
	fwrite("Makefile", "".join(makefile))
		
