#!/usr/bin/env python3

import sys
from os.path import dirname, basename

dir = dirname(__file__)
if basename(dir) == "scripts":
	sys.path.insert(0, dirname(dir))

import nuvolasdk

sys.exit(nuvolasdk.run(".", sys.argv))
